# Generated by Django 4.2.7 on 2023-12-07 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mealplan', '0006_shoppinglist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='mealplan.food'),
        ),
    ]
