# Generated by Django 4.2.7 on 2024-01-03 05:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mealplan", "0008_category_alter_food_name_alter_ingredient_food_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Day",
        ),
    ]
